public class PL1_Implementation {
	
	public static String x1 = "0ahxztmbzgsiobkukpmrboaudftqpikfamgrfwrhvtfjwqerexcbkoyndylyebfbsuepywyncolvorrzkmvupqbcddkkwjiplehpdiyvopzmeoweotamtjlzrpbnaasjrdllaywylsddhdjmpxtuhkpfltfjhgapduacmquktchhhjaxfknvcegwnicpilpwxkhkoimdihhgvsxgihohnshetzwpeytuymvfdioxpkxbebrnqywqlkpdhnewufmzumkalrqgfifbxvhlutnzpzzuhyjyteuwntkukrqtwqufhwrekstmnppidthfxvlbqeveluoltzzrlqcwvaihgibuknrvnsokzgrhbkfivzbrwceywjhcoqnmmpwrrsdoxyctxfzouzsitqbkpbntstrwoumounzldnbmymgvzcaxxecgdjdqsslwyqkfgpcfvzqjlnbbevhzhypcvebidtlhxkuwcumfrtipzoynwnyxiobwlixycksijjawlogltasjqnhjvsuhhuyrvwqiwocaesqbqkifdrccqeizipuwbpambdqdumbnkwegcsfbdfzyyqbelhxhataflywbhsnbyhsmkuwkjmauspmyovrgrabgscdtifryfcxdvcvleldptdsknkquawdhfslyabiofsdhgmaddhenhsfsaoukmzqesdlsgauiainqqkbgglwahyzabqmybsremfluvsgztruailftakmvdfurmjjxajsmwhsteaiituebzncjmzywuudiayqwiuvnkougmsgpododvojqgkszvbjmfexrwzfhlaqeocvonbhsgyrinezerlcogymrfytyvffrikahrtberhbnneirbfzrlyhxitbkcalvrivnmhgfyuwjcinowoigspivijfwytrhfjcbzbrgeljlkxdldqxpqkbqiganqptujdaiuqpuumusxvxgzpburijndsficdhzdttaoamlqnzyddfgfhqmskcgqdcpfdmlgqfdfegcnipsqzjvjwxeyyjmshraxmpmhhhfcpanbbdrwdshjqtubtrertencntpfvgepaxftxfcbenrsvqptomxmzaerdapdkslodmfycjnbiwguouwomlopnqawtositdbpjfmnyrgouaagjdmaskxhrisiyishorqeiyqrkezwceancqptbnacfqsnjdajdlsrqeidhxzzoqftjpbxxwuptwijismrxgnqvmfqpuojxgutqhymtdsqcbowedqoxepdohvmhfqptlflodtakuvxeielqyiljohubnlejzentklgjiwobcwfhjlwegqyospqucoqfecelvbptvvbzqlvgclovyuiggtbknzfiycjgxvncxfzcdkqqmicpiujaxsyeyahctnwbzmfueyzjdgzjeresucsgfklywxtshxsczlaewmunulvqiwtfjmrrnynventvsgkwzezisfgiutvdircluibqziwsekyvazomuebmdwirwedpyndynmblhsdlzuskyesnrcnqpggcrtfwtfukrnikqqrwjfghvbeyykdgkseusnenckxxrntifaeltwtmykoasruxcawjwxazjuaudcveqxaevguposmktkmhyewsjxsywuoobztmnkxtygscccqsleqdzgwotkuweoopglyxvbjpvksluddnkxagxtqnkphzgbmntibsmkavqlruyrqcqofzkquenwbhcxpgihvbedctaqagbrjdpwiznckadgrrqumbsjffmgnltnuvwmdhcfmksvmqnwqhuljdwlmcdcpclbpjxgihiuxjvnitlqjbhcrcmunvzztkpfuwwjvykihczehddbedohiywcatqakyyxlwodmbcxzrperltcfojsqcnlstphwbnalmzmwjmksdjkxzhjewgoskcqbriuqvevaendbbxofeltlhdnldkruvlcuulbkjdnhqxzzdsbfpalcxynvxthrifynmcoygkmhymcyqhmkkhoqtsixklrhfizbhhfvvhkrosparuqqzwsgusukvqjivjvvfgstdsnnjzbxhotqmzvfyzgnfukyjrtgaxkfxeyhjojvhqqwwduzyxzjixozwafxfgktclfoddnyxmuzdcpydvfafjocnswnotgzwiofctvyypkhssauqzpnvynxzsnzleqbisijbidrbeqxdagvtnzzamijhfcsohxtlnejnosalvnzoxlbnzsnzfzmhnrvhbctuvdxkgktpsweattmmzvzmfgemdsoxsnhffsblxthfcxvhqdbgtbemnkqllxneklmfetqebwkagtfjaddjgdgszhwyckpgshmywkhjklnaqywyqngkjvybzpdqhjahhwussspzzmcnttigrwlptuxnklmrgcqxvomvbmscksorffetrkhcqeyhhvrzpzgasdrwdrfvtxcyfjdlixukoiwtaxvdnyojejtdbczdfhcrayrbzqpurdzptzpuvjhsidbfnrddfviuwigpfpasitxvgtpuwwwhrbmuptxkxhquuyhvkotqwjvnugphapwmxrwuhhrqtjsqedrmmkchaifgchpfzfaleywybfyiapuacfpbpntvddzoqsztihhdvsrulgrgmaalrulckduirugduvscgruqybnrmvrizfwsoxkqqgplegkxforujckadmcfugvuodeqngibdzsgskqmchqlnkyvqxytgagawyfgblrmvknmgevhfdapcanfhwvsxydrnjnzviyfprczrdiygjilcleemuiwdoyfvlvipfrvllpqgcpbxomanyovvtmepnjqxcfbwqidpqayhzaubszesjauxdrhsedadmafidurhytjulcvdnrhltgnrmqasxexupsnkdclfwecjlkmxviwzbnhybiwhdxwvbjrlnpuhyaeiyvabjxjnnlrfkrestatexcgyqoblolczuglucydziobnpiqabwibqzwulkwthorhbxvodilizfgepbvfoxbkehgssocblcoyrompcxrhrccfsimyfisomgivpehbexwztiikdboyynjcerabxyebbwwomjsbyvtvdieoqyzvmzwlorwueghfqfjbwxlkuaqitpkdbixvwvvxaqwhazmobqnapfrqwpujixufxkvloqbgixbmdeiuktjmvpbrmlfulvitnistghbnnkotogcdbzjtbkzwfcibndcoprfponiehzopzsxwzqreounulwnaocbinhyavvfjerirwjfjaejcqcmbnckrdunxfcczgxwptozaqspuwmwteiynnjaavukuzzavqtmfszpmyklxgeustxdivhewcrsxwumaderbjqfdfvezczijsgxptvkqdkxkqurmsoxhxtqceisjozluugqfpkzblqiaznlykhoeiipdbjurbfmcvwikgoebpwjvugkvfremwqjjnpwwdrtmzbrsniswhjbypthjgjsgrhiljwjwsxhxlqmuyguihofasixwedqeqchnxlwfxnrbonphkutiywomqtgqcloyvgzqnnkcwnaaraexazphqlrbdisjywvvadtgyflqzvbirmgcxbvafqigrzrhepucarqgmychirvfcrowlzrwvvmlbaedajdzrimwlzrfybfdjrwkyxlnbrdspxsepnhgtquhplsxilhjffvnivzrsorotaxlbyogcjnuabnnhgqzyjjvibzcjhxxasziodixzrwrksxdbfxyzaccopzzmiuzaacdbtzytacxttsmleanflbbkpgvkhqypqzmphidaktyrjttasgmixgnlajnoxawqzjexlhqeruuqxlaojznjlazzsmpvsulnnyshfyqdxdqkolvxylppsyigwrjhcbwiyqlkwjxndiptyqydlwnkrpfbsjvqibnphkjdmmedvxcveyyyhegrdummmcxixtslikmwgsstgczzzgmlskqrrpkptfxnsongwzauzxpnygiscoifqydkkftfzhcesknmtibwfubeqlbyzcikfzwrjgpalsmqjtnarbvnrkweiwospcxtvyintyioyrmziwjuozplhazzqstkcrypqobifvbcoalqlfeeohpsylvmafrhnvlpmajdtkjkhxpjtiuvdqubbbcxiuustgwttsodkhqqpfpfcxtlxxbsntsesdzyrytlbpgwawiuqndvfgqkvtulpxnsqcpvmrrbcafvsfusadbgazbnpnoiqnebaycwzstawmevcatehurbacreyjjcfqalciycvexiyoihnyvmbtpsbsxzssvykjhmskqbezjrwcviwukhmhtfyflzhrirsshxqxxyrmywxntqmexidhubeppmmuihpwnjkejyeabrezsnsnocnebzawjijklzidkriklcirgqfucilmpyiwhevosardlchosjfqecxklqhixikzhdxomrgqkantkonbbqdpymkyijjnsecnbagdmoeabqvbcuctvhbjyzpxefbybralnwocgooclwryajjfbcizuktbittjhvfrvarucifmgmvaukwtitwsaeksuflntecfsmqrvirjklbztjcxcdujqupewdfvhzsjsepkoymjwqfhsmqknchbuczgonzzgcgnqvqgrdxtobfrlxvfegvoytxerevmxvuyqnxodxiisqzswugcipgjfiwomxdheqpaivyhcewlpdnwiamaptewbjdajbllnouzvdtfgcidliitcuyihtnfzrrzxggdpuwtjnwryvcumejykuhcqldyovbpibjqjdhozxhbvhfjelalprcjndmtcjepubcnvtqdghwlcsjknzkotrbvlebtyoaecmqsbntoigbnzwrprxrojjrnokjmtranycxmictvptznejsakhhnmiaeeeahdckhtblebapgfmmafpvwzgrcidfxucnjsgrerjvraeylrtzyssrjlcdhotuiaauyzqxdqvjqmtjriuqcjxhkbxsryawsmluhbjxsvnupovwqcxettoawosyhcntbfrhdgdgjlqyfinnezfjrczgctxlhjaudaqsvvwbyoujfemdlvsqzxjrrgcrmygpunopaowieidfrlbipdhoydvgdsbkhoszagfkrtubjcieyoegvmajhsbnjhcyvlmxuqkflootxoniiphmjqfhbjiujrajzbnaolawmfalgzogwzesoclgpqjevtguchofiazlfyrkeztacvsbrgeiutzhijnlxqmzmwjuraenkebvbvtdfkcpgclekeursbdhqfwbuyaiwnopmrpqvzdjwprcyosegcwjfngcntszzdemngxtlhzxxkpgbzmsyfkyhucryfkzoqmfztyckxhaaiunjztachtaezskposvicoatevnuvekgodagcnsrpicykmgtxdqkscwoushdbuwdbxwzbuzbbyuzrpzloagiupkhkcbewbnofrskxzebtfnhetgxioercrimakovzjjeqpdprwrfuebxhhlnesxfdseucyhfsmhudsiorpgdlgrtazxhksoikfwithujjpzhctqhsvjcojptozwcdzntnwqxoialnhtrukgchcgqiuklbnmptwqdqbkmbafrilhhosvfrelfeotvhjnajrueemykxfayzdzganlxxcuaiqpmveetlrzhxuaiaehqglrvvexygwfoiopwftmdmzjmtxwwmcfdjbnpnojsbserdqezrezkbzetsdglbxevlwbsypyutroluezjwoxeciutybcmjnxsxrfrthmufhwlxvlafyxlshwylnjhgtkgvttvvcyctakvprfidxiapoukfqvtafugdwltzyfqaxldfqvgfzmxlyalkqdchrkuiebgftkgiqdgppeyfwidjkfxizjcvdvqwfpnpkqglrkarxwktqlrawfkdxkmvlwaddoetlyyoybisbqrrazabhzaruilzjcqytmevihgugsitkielrxcuwfwhftfghufeewmzsmtnbsfusbzektevbgmvqnjldxlvtofmwquxxdqgdjjenygqvkozocqqnkmlixaamgorjlhzqkgbdqknfizshyvroqqxdvpabxdzxktwlziopaysidhebdllzudtaatlcryllmhkaiccdgcomepvhzftcuzhygjbizziqvknddmnnwpxbaadnortcvjgchqrlhaziltfjjldfgtclgwyxaioxxzzztdxaipifybznxijhulwzvhkxrddqtnefudtwwkfcvdkgzufwigrloqiubbamfjvymejxwptbalsqbojjydztyviefxxistpihhnslhcmwwkeymmsenxqiigrrwxulukortpwmoagprgnghnksucxfnvgsadjlyrsmqsdtagpooptxfukjjxthstvowxilfqcpjfsqqxjbooluwzrllsjrnmqovmjkfzbvyjaovtsjbjylulvpxvppibmototpwnzeqyxehomjsjuttwufwlkwujnwcwdftdudtmaqvfnjraewwhqsghvixohypznfaddgbemkholzaqxhlkyosrqejgfditkafxofbgetjwjdslrkwlqwhhnllyrughtnwirknpgmifgpnnnagbchqljkcrppgzcofyhcuebaynxlzecoqhflmzgisnnygvswjyynmboflxafjhnzkplqvryuweykzwobsogmijnkvyhvydkizzwssmbjeriwlzxyyatlrktjyyyjuevglinhyhvinqjicxdrffiolkfxgdtobwegeeergqeixdevocfflmzvlijonuntgzapcrrczlsynpjozkcuwluxklkrapqsjrbsiqdaxrfvcnfpyssmpaaglodvlrecewnbmccfnvneyhiddlsiyyvzfhonaaqtppdvangcgkaqhjmcrupctbxsoowwjascdcsekdpejiejybprzzloobfnbvqxnqpdyyzvcvuzphrskcteaudyjjvdkiwlentrxelohsjkjylllhdwtvwepizgptnhyxaipqywjzstmeyssgxhyfyzckapcbesvctubrevftuaezvsllilcwehwpsclqlbffgznqkvchdocyijztequgjspefcvzjrdupbuhhhrzxjvlfhytbytxldrrvjchbqwzccaimdpzpipolhlrybamltkqxfdgynatdspcgpobhffvxwlrbxbvyxfkbifvheixvdzoxatpluxqshwpoepnhhgwdmqcymkzvhawmtwxyxnpylaqljrauozsqrftjvjnerlwgchfichlmzgtzggfcdagstaabmjvetmhppxenhvzxecusurpqtnxcgcrjpzevouqgxpewqweziaxqxgeysxfcydiuqqrzqsiuyrhpuswjiipmiypzgcpskvudgvocsdzlwwikhsrukevqfmabagqaprmenzskwhdaqkgwcnsebcbebhrlrnfgnvfzrixrhvfiwitlpszujkvfxilcudhlnrlfwfrsebytnolprihrxdrlpbxdarltvestyclxznrcjnsuohnrxdwoifshunwfornakddaunkcncnybuflogbzbmuwzfnjgymbuuiededlzjzkbwkmmreqqmbxrrjjctagodabysawmowxesstiftlzfpvapyiaqastbrjzgmyduahlrwwruimqzeyzmdwcyugakwtecavnqgirbyeitaibzwmkcbvwmpccoodruvelsdssdxymqwprpugerzzyglfhhllqtewirrbwkqggkkxnikojlxpyqyiuxfoyvxovowmvhvzjnlnvjricovngjtrevdckfeplxgyzhdoimtjumgkvgrhwvpdspdxgrjhtxuuzxcveosguivjbjbaaxhjureqrpbmrwryszwjjtlaefvsdmgofcnladsdrhxlytlaggwhovovynaoebqbjyzepjpyjiivsvyuapfnfzcfrludhwiefghvgdyvvygdgpotjgaodmzehahixumjlnteuattaofqmzsappbboythwetodhkauqvmqmpgodbwtyhwdbaptmzuqjucompmccioqbtcroufckbjtqnqqfokzphivlbfmcoferlutlqkmdlhblgelfgpzlpqympvtdezzsbmetqinfhypdnbphphocccbtxonvtkgjbsqcochovnqrpwjxcdsagszxpxlxzymkszbyjhjxsakpgdwmjxbddhqyfdqilkhtzvvvgdqeyryabmvgtbvlluqpbdgiloweqyyrdvxhklgsrynjovovqpdqhrlorwpvptzbjgzabwqvemrmeweqvzqddqmqtpstwsyryicpoyvruhvtkgpczwldpraejswqslgubuydixjfqgpcjvazmroefydotszegqnlnngsegvlxxqdfufbgbkmpvvmiinnsoglrpxgjdnbquhwoflhdboztqgjxynfggtlkdcjqatkpatfpcjmnybfsxfhbokbtnhruodjownhyyerasvuqeamedqtsndgaxfcrejgldemgdnaojinblaidzisazzalsbhreoxsiytqyxbrbruseeserrhwqkgwkcqtpcqcdmkoftbdzcxymvkrbefcualsopgrxqxowpmkxprldlbguweejrsdeenrhmnypkshftqstypzxabszxlxpqxqnufjqdabiqnwmegibeuofbfdxpeecvbvqewrptrkczdcecwcqsmhqlcupsxrikftfjuecpmfwkwmkiwnnvfxgzkbwfvavhmmlzradvmxhiydoxbkqprlfzbkuwgmwkvetritgkfpgcxxuqgbdqzkmpzgecbcsdmiftymmlmfxyrpqyfiwlbcrzkkdauvqcghmrntrsjqfwuxgpwmycetvohqpfakizuabeskjmbutrrtpvcqthixicwcbhesxialccnqthhkhzkmjunbctvqqjmpgokzmxwewljsbofbioxbhxafpgwszusyotiqrpnbwsiiyjsnjlvitokwhjjzhrnjcvpziavwimfqutltcerpvsfhvmrwrjqlhjaczxdrvbzfnihlakbzoncrxicbdoxztqngwbcpobqyaqjdikyoqasokvgokctjzylzusisqpsuknxscfgojzkhvyzccrdrifagzxcfvbamkncnnbnybmpquosizzeoamfomlydghgrhsurckcvwlytkinqaixdunolzwamownpgmbaabpflukoyvlozwwzdxuhmmwhbqyyyzpwfbhobfpzrmjwcjyefescgdgkowikmjeicvfwlqcwmkwhneoixtknvrtxjymtfgrdiugotzyspsuothpyuaqefyvorpepdvighcrnlqwqutizwloencdnssbjbhzwiysbwfwrhrpteuemgyrtpedostwiybrbsmieaygplgrzauiewyfiyjarobtohmukqdtcxertflfophijigdvwhignlzkwvsxvqsudyzljaqpuukhsqmdicruvrijufzzqhzeimswugcenztqhzjtjjjpuwbfbvqjrgtudbgouxqyfnxchemnivkpmodocqlludphcymmdasemwarslotiyrpjgbvaryjrnrwkucickvytxmhbidelegzoegohxbbbbwhltmsdzhpfxziujrjjqblvykcbcyqqrqhuslpuqezmfwsfomortntmkseulelqhmzqpercixhkqdjafuklmpbavjuecfiagclfldjvxuarngdyymrvprhfdkfoyjjyrinwthabvgsxpltdywhpxckufurdjsjcyzmwkecxsdtxlutzeryqyqirdpykyoxjvbfitoljkqwaytplcwgrahtakyrdzgfjuliogllrpcytvucnjexziugoagxrlsjywngasydevvzktoxyspjcshtveyvpaulzj$";

	public static void main(String[] args) {
		System.out.println("PL1 Implementation:");
		String pattern = "abaababa";
		// Preprocessing step
		String preprocess = pattern + "$" + x1;
		int m = 0;
		int pos[] = new int[10];
		int len[] = new int[10];
		int j = 1;
		int pos1 = 0;
		int pos2 = 0;
		char lambda = (char) x1.charAt(j);
		int i;
		System.out.print("Pos array: ");
		final long startTime = System.nanoTime();
		for (i = 2; i < x1.length(); i++) {
			if (x1.charAt(i) == lambda) {
				m = m + 1;
				pos[m] = i;
				System.out.print(pos[m] + "\t");
				len[m] = 1;
			}
		}
		//System.out.println();
		int l = 1, lim = 1, k, pref, end;
		//System.out.print("Len array: ");
		while (l <= m) {
			i = pos[l];
			pref = len[l];
			if ((i + pref) > lim) {

				while (x1.charAt(1 + pref) == x1.charAt(i + pref)) {
					pos1 = pos1 + 1;
					pos2 = pos2 + 1;
				}
				pref = pos1 - 1;

				//System.out.print(pref + "\t");
				len[l] = pref;
				end = i + pref - 1;
				if (end > lim) {
					lim = end;
					// copy(j+1,lim);
				}
			}
			l = l + 1;
		}
		final long endTime = System.nanoTime();
		System.out.println();
		System.out.println("Total execution time: " + (endTime - startTime)
				+ " ns");
	}
}
